version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: arami-keycloak
    command: ["start-dev"]
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://host.docker.internal:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    ports:
      - "${KEYCLOAK_PORT}:8080"
    # no depends_on: Keycloak will use host.docker.internal to reach local Postgres

  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    container_name: arami-minio
    command: ["server", "/data", "--console-address", ":9001"]
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - minio:/data

  pgadmin:
    image: dpage/pgadmin4:8.10
    container_name: arami-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: "40"
    ports:
      - "${PGADMIN_PORT}:80"   # http://localhost:5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    # no depends_on: pgadmin can start independently

volumes:
  minio: {}
  pgadmin_data: {}
